version: '3'
services:
    postgres:
        image: postgres:11
        container_name: postgres
        hostname: postgres
        environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
        ports:
          - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        links:
          - postgres
        depends_on:
          - postgres
        environment:
          PGADMIN_DEFAULT_EMAIL: samuelolle@yahoo.com
          PGADMIN_DEFAULT_PASSWORD: leicester
        volumes:
          - pgadmin:/root/.pgadmin
        ports:
          - "5050:80"
        restart: unless-stopped
        
volumes:
  pgadmin: {} 
